version: 0.1
phases:
  install:
    commands:
      - aws cloudformation package --template-file template.json --s3-bucket {BUCKET-NAME}
                                   --output-template-file outputTemplate.json
artifacts:
  type: zip
  files:
    - outputTemplate.json

